apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: application-pods-autoscaling
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pandacloud-app
