apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-rolebinding
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prod-admin
subjects:
- kind: User
  name: prod
  apiGroup: rbac.authorization.k8s.io
